config/routes.rb
Rails.application.routes.draw do

  root to: 'jobs#index'
  
  resources :employees
  resources :jobs
  resources :assessments

  devise_for :users, :skip => :registration
  post 'manually_assign_job',            to: 'assessments#manually_assign_job',       as: 'manually_assign_job'

  post 'export_data', to: 'assessments#index' , format: :csv

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  validates :job_id, :employee_id, presence: true
  acts_as_paranoid
  belongs_to :job
  belongs_to :employee
  def assessment_type
    manual? ? 'Manual' : 'Automatic'
  end

  def self.to_csv
    attributes = %w{id assessment_type employee_name project_name created_at }

    CSV.generate(headers: true) do |csv|
      csv << attributes
   
      all.find_each do |user|
        employee_name = Employee.find_by(id: user.employee_id)
        employee_name = employee_name.name
        project_name = Job.find_by(id: user.job_id)
        project_name = project_name.name
        created_at = user.created_at.strftime("%d/%m/%Y")
        csv << attributes.map do |attr|
          case attr
          when 'employee_name'
            employee_name
          when 'project_name'
            project_name
          when 'created_at'
            created_at
          else
            user.send(attr)
          end
        end
      end
    end
  end
end

app/controllers/assessments_controller.rb
require 'csv'

class AssessmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    get_data
    csv_data
    respond_to do |format|
      format.html
      format.csv { send_data csv_data.to_csv, filename: "Data-#{Date.today}.csv" }
    end
  end
  

  def new
    @assessment = Assessment.new
  end

  def manually_assign_job
    assessment = Assessment.new(assessments_params)
    assessment.manual = true
    assessment.save
    
    redirect_to assessments_path(assessments_params)
  end

  def create
    @employee = params[:options]
    if @employee.present?
      @job = []

      Job.count.times do |j|
        loop do
          @find_job = find_job
          if !@job.include?(@find_job)
            @job << @find_job
            break
          end
        end

        @employees = Hash[@find_job.employees.map {|e| [e.id, Assessment.where(job_id: @find_job.id, employee_id: e.id).count]}]
        @employees = @employees.sort_by {|_key, value| value }

        @find_job.number_of_capacity.times do
          @employees.select! { |emp| @employee.include?(emp[0].to_s) }

          if @employees.first.present?
            emp_id = @employees.first[0]
            created_at = params[:created_at].present? ? params[:created_at] : Time.now
            @ass = Assessment.create(job_id: @find_job.id, employee_id: emp_id, created_at: created_at)
            @employee = @employee.reject { |val| val == emp_id.to_s} if @ass.present?
          end
        end
      end
      redirect_to assessments_path(created_at: params[:created_at])
    else  
      redirect_to new_assessment_path
    end
  end

  private
  def find_job
    if Assessment.where(created_at: params[:created_at]).blank?
      employee_with_minimum_jobs = Employee.all.min_by { |employee| employee.jobs.count }
      employee_with_minimum_jobs.jobs.first
    else
      Job.all.sample
    end
  end

  def assessments_params
    params.require(:assessment).permit(:employee_id, :job_id, :created_at)
  end

  def csv_data
    if params[:created_at].present?
      date = Date.parse(params[:created_at])
      assessments = Assessment.where(created_at: params[:created_at])
    else  
      assessments = if params[:from_date].present? && params[:to_date].present?
                    from_date = Date.parse(params[:from_date])
                    to_date = Date.parse(params[:to_date])
                    Assessment.where(created_at: from_date.beginning_of_day..to_date.end_of_day)
                    else
                    date = Date.today
                    assessments = Assessment.where(created_at: date)
                    end
    end
  end
  
  def get_data
    @assessments = csv_data.group_by { |assessment| [assessment.job_id, assessment.created_at.to_date] }.transform_values do |values|
      job_name = Job.find(values.first.job_id).name
      employee_names = values.map { |assessment| Employee.find(assessment.employee_id).name }
      created_date = values.first.created_at.to_date
      { job_name: job_name, employee_names: employee_names, created_date: created_date }
    end
    
  end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper

  def employee_name(id)
    Employee.with_deleted.find(id).name
  end

  def job_name(id)
    Job.with_deleted.find(id).name
  end

  def count_days(emp_id, job_id)
    Assessment.where(employee_id: emp_id, job_id: job_id).count
  end
end

app/views/assessments/_form.html.erb
<%= form_for(@assessment) do |f| %>
  <% if @assessment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
      <% @assessment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="div-assign"> 
  <div class="field">
    <a id='select-all-button' style="cursor: pointer;"> Select/Desect All </a>
    <br>
    <% options = Employee.all.pluck(:name, :id) %>
    <% options.each do |option| %>
      <%= check_box_tag 'options[]', option[1] %>
      <%= label_tag option[1], option[0] %><br>
    <% end %>
  </div>

  <div class="form-group" style="
  margin-left: 15px;">
   <%= date_field_tag :created_at, params[:created_at], value: Time.now.strftime('%Y-%m-%d'), class: "form-control" %>
  </div>
</div>

  <div class="actions">
    <%= link_to 'Back', assessments_path, class: "btn btn-outline-info" %>
    <%= f.submit class: "btn btn-outline-success"%>
  </div>
<% end %>


<script>
  $('#select-all-button').on("click", function(){
    var cbxs = $('input[type="checkbox"]');
    cbxs.prop("checked", !cbxs.prop("checked"));
  });
</script>

app/views/assessments/_manually_form.html.erb
<%= form_for Assessment.new, url: manually_assign_job_path do |f| %>
  <div class="row mt-5">
    <div class="col-3">
      <div class="form-group">
        <%= f.label :Employee %>
        <%= select_tag 'assessment[employee_id]', options_from_collection_for_select(Employee.all, "id", "name"), {include_blank: "Select Employee", class: "form-control form-control-sm"} %>
      </div>
    </div>
    <div class="col-3">
      <div class="form-group">
        <%= f.label :Job %>
        <%= select_tag 'assessment[job_id]', options_from_collection_for_select(Job.all, "id", "name"), {include_blank: "Select Job",  class: "form-control form-control-sm"} %>
      </div>
    </div>
    <div class="col-4">
      <div class="form-group">
        <%= f.label :Date %>
        <%= f.date_field :created_at, class: "form-control form-control-sm" %>
      </div>
    </div>
    <div class="col-2">
      <div class="form-group">
        <%= f.submit 'Assign', class: "btn btn-outline-info btn-sm", style: "margin-top: 32px;" %>
      </div>
    </div>
  </div>
<% end %>

app/views/assessments/index.html.erb
<div class="card-body">
  <h3>Manually Assign Job</h3>

  <%= render 'manually_form' %><hr/>

  <h3>Previous History</h3>
  <%= form_tag(assessments_path, method: :get, class: "mt-4") do %>
    <div class="row">
      <div class="col-4">
        <div class="form-group">
          <%= label_tag :from_date, "From" %>
          <%= date_field_tag :from_date, params[:from_date] || (params[:created_at].present? ? params[:created_at] : Date.today), class: "form-control", onchange: "this.form.submit();" %>
        </div>
      </div>
      <div class="col-4">
        <div class="form-group">
          <%= label_tag :to_date, "To" %>
          <%= date_field_tag :to_date, params[:to_date] || (params[:created_at].present? ? params[:created_at] : Date.today), class: "form-control", onchange: "this.form.submit();" %>
        </div>
      </div>
     <div class="clear-ex">
     <div class="col-1">
     <%= link_to "Clear", assessments_path, class: 'btn btn-outline-info btn-sm' if params[:from_date].present? || params[:to_date].present? || params[:created_at].present? %>
     </div>
     <div>
     <%= link_to "Export to Excel", export_data_path(from_date: params[:from_date], to_date: params[:to_date], format: :csv), class: "btn btn-info", method: :post %>
   </div>
     </div>
    </div>
  <% end %>
  
  
  


  <table class="table mt-5">
    <thead>
      <tr>
      <th>Worked Date</th>
      <th>Job</th>
      <th>Employee Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
    
    <% previous_date = nil %>
    <% @assessments.each do |job_id, assessment_data| %>
      <% created_date = assessment_data[:created_date] %>
      <tr>
        <% if previous_date != created_date %>
          <td><%= created_date.strftime("%d/%m/%Y") %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= link_to assessment_data[:job_name], job_path(job_id) %></td>
        <td><%= assessment_data[:employee_names].join(', ') %></td>
      </tr>
      <% previous_date = created_date %>
    <% end %>
    
  </table>
  <div class="pagination">
  </div>  
</div>

app/views/assessments/new.html.erb
<div class="card-body">
  <h3> Assign Job </h3><br>
  <%= render 'form' %>
</div>