config/routes.rb
Rails.application.routes.draw do

  root to: 'jobs#index'
  
  resources :employees
  resources :jobs
  resources :assessments

  devise_for :users, :skip => :registration
  post 'manually_assign_job',            to: 'assessments#manually_assign_job',       as: 'manually_assign_job'

  post 'export_data', to: 'assessments#index' , format: :csv

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  acts_as_paranoid
  has_and_belongs_to_many :jobs
  has_many :assessments, dependent: :destroy
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  def index
    # @employees = Employee.all
    @employees = Employee.all.page(params[:page]).per(50)
  end

  def show
    @employee = Employee.with_deleted.find(params[:id])
    @assessments = Assessment.where(employee_id: @employee.id)
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_path, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_path, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name)
    end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group mt-5">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Name" %>
  </div>
  <%= link_to 'Back', employees_path, class: "btn btn-outline-info btn-sm" %>
  <%= f.submit class: "btn btn-outline-primary btn-sm"%>
<% end %>

app/views/employees/edit.html.erb
<div class="card-body">
  <h1>Editing Employee</h1>
  <%= render 'form' %>
</div>

app/views/employees/index.html.erb
<div class="card-body">
  <div class="row mt-8">
    <div class="col-9">
      <h5>Listing Employees</h5>
    </div>
    <div class="col-2 text-end">
      <%= link_to 'Add Employee', new_employee_path, class: "btn btn-outline-success btn-sm" %>
    </div>
  </div>

  <table class="table mt-4">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.id %></td>
          <td><%= link_to employee.name, employee_path(employee) %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee), class: "btn btn-outline-info btn-sm" %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pagination">
  <%= paginate @employees %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="card-body">
  <h3>New Employee</h3>
  <%= render 'form' %>
</div>

app/views/employees/show.html.erb
<div class="card-body">
  <h4><%= @employee&.name %> Job History</h4>

  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Job Name</th>
        <th>Worked Date</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @assessments.each do |as| %>
        <tr>
          <td><%= as.id %></td>
          <td><%= job_name(as.job_id) %></td>
          <td><%= as.created_at.strftime("%d/%m/%Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>