config/routes.rb
Rails.application.routes.draw do

  root to: 'jobs#index'
  
  resources :employees
  resources :jobs
  resources :assessments

  devise_for :users, :skip => :registration
  post 'manually_assign_job',            to: 'assessments#manually_assign_job',       as: 'manually_assign_job'

  post 'export_data', to: 'assessments#index' , format: :csv

end

app/models/job.rb
class Job < ActiveRecord::Base
  acts_as_paranoid
  has_and_belongs_to_many :employees
  has_many :assessments, dependent: :destroy
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all.page(params[:page]).per(50)
  end

  def show
    @assessment = Assessment.where(job_id: params[:id]).distinct(:emp_id).pluck(:employee_id, :job_id)
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_path, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_job
      @job = Job.with_deleted.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:name, :number_of_capacity, employee_ids: [])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-5">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Name" %>
  </div>
  <div class="form-group">
    <%= f.label :number_of_capacity %>
    <%= f.text_field :number_of_capacity, class: "form-control", placeholder: "Enter Job Capacity" %>
  </div>
  <div class="form-group">
    <%= f.label :employee_ids, "Employee" %><br>
    <%= select_tag 'job[employee_ids][]', options_for_select(Employee.all.pluck(:name, :id), {prompt: "Select Employee", selected: @job.employees.ids}), {class: "form-control form-control-sm", multiple: true} %>
  </div>
  <%= link_to 'Back', jobs_path, class: "btn btn-outline-info btn-sm" %>
  <%= f.submit class: "btn btn-outline-primary btn-sm"%>
<% end %>

app/views/jobs/edit.html.erb
<div class="card-body">
  <h1>Editing Job</h1>
  <%= render 'form' %>
</div>

app/views/jobs/index.html.erb
<div class="card-body">
  <div class="row mt-8">
    <div class="col-9">
      <h5>Listing Jobs</h5>
    </div>
    <div class="col-2 text-end">
      <%= link_to 'New Job', new_job_path, class: "btn btn-outline-success btn-sm" %>
    </div>
  </div>
  <table class="table mt-4">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Number of capacity</th>
        <th>Employee</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr> 
          <td><%= job.id %></td>
          <td><%= link_to job.name, job_path(job) %></td>
          <td><%= job.number_of_capacity %></td>
          <td><%= job.employees.pluck(:name).join(', ')%></td>
          <td><%= link_to 'Edit', edit_job_path(job), class: "btn btn-outline-info btn-sm" %></td>
          <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="pagination">
  <%= paginate @jobs %>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="card-body">
  <h1>New Job</h1>
  <%= render 'form' %>
</div>

app/views/jobs/show.html.erb
<div class="card-body">
  <div class="div-job">
    <p>
    <strong>Name:</strong>
    <%= @job.name %>
    </p>
    <p>
    <strong>Capacity:</strong>
    <%= @job.number_of_capacity %>
    </p>
 </div>
   
   
  <table class="table">
    <thead>
      <tr>
        <th>Employee Name</th>
        <th>Total working days</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @assessment.each do |as| %>
        <tr>
          <td><%= employee_name(as[0]) %></td>
          <td><%= count_days(as[0], as[1]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>